name: carapp_flutter
description: CarApp - the app for buying and selling cars
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cars_api:
    path: ../cars_api
  cars_api_firestore:
    path: ../cars_api_firestore
  equatable: ^2.0.3
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  go_router: ^3.1.1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

