include: package:very_good_analysis/analysis_options.3.0.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"
    - "**/localization_exceptions.dart"
  errors:
    invalid_annotation_target: ignore
