name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-cars_api:
    uses: ./.github/workflows/dart_package.yml
    with:
      working_directory: packages/cars_api
      check_formatting: false

  verify-cars_api_firestore:
    uses: ./.github/workflows/flutter_package.yml
    with:
      flutter_channel: stable
      flutter_version: 3.0.1
      working_directory: packages/cars_api
      check_formatting: false

  verify-carapp_flutter:
    uses: ./.github/workflows/flutter_package.yml
    with:
      flutter_channel: stable
      flutter_version: 3.0.1
      working_directory: packages/carapp_flutter

  build:
    needs: [verify-cars_api, verify-cars_api_firestore, verify-carapp_flutter]

    runs-on: ubuntu-latest

    steps:
      - name: noop
        run: echo 'noop'
